export enum AggregationTypes {
    COUNT = 'COUNT',
    AVERAGE = 'AVERAGE',
    MAX = 'MAX',
    MAX_BEFOR_MINOR = 'MAX_BEFOR_MINOR',
    DIV_VORTAG = 'DIV_VORTAG',
}

export const config: any = {
    heizungssuite_da_heizen: AggregationTypes.COUNT,
    heizungssuite_da_heizkreis_1_pumpe: AggregationTypes.COUNT,
    heizungssuite_da_heizkreispumpe: AggregationTypes.COUNT,
    heizungssuite_da_pufferladepumpe: AggregationTypes.COUNT,
    heizungssuite_da_quellenpumpe: AggregationTypes.COUNT,
    heizungssuite_da_reststillstand: AggregationTypes.AVERAGE,
    heizungssuite_da_verdichter: AggregationTypes.COUNT,
    heizungssuite_da_verdichterschuetz: AggregationTypes.COUNT,

    heizungssuite_ia_anlagenfrost: AggregationTypes.AVERAGE,
    heizungssuite_ia_aussentemperatur: AggregationTypes.AVERAGE,
    heizungssuite_ia_heizungsdruck: AggregationTypes.AVERAGE,
    heizungssuite_ia_isttemperatur_fek: AggregationTypes.AVERAGE,
    heizungssuite_ia_isttemperatur_gebläse: AggregationTypes.AVERAGE,
    heizungssuite_ia_isttemperatur_hk_1: AggregationTypes.AVERAGE,
    heizungssuite_ia_pufferisttemperatur: AggregationTypes.AVERAGE,
    heizungssuite_ia_puffersolltemperatur: AggregationTypes.AVERAGE,
    heizungssuite_ia_quellendruck: AggregationTypes.AVERAGE,
    heizungssuite_ia_quellentemperatur: AggregationTypes.AVERAGE,
    heizungssuite_ia_raumfeuchte: AggregationTypes.AVERAGE,
    heizungssuite_ia_rücklaufisttemperatur: AggregationTypes.AVERAGE,
    heizungssuite_ia_solltemperatur_fek: AggregationTypes.AVERAGE,
    heizungssuite_ia_solltemperatur_gebläse: AggregationTypes.AVERAGE,
    heizungssuite_ia_solltemperatur_hk_1: AggregationTypes.AVERAGE,
    heizungssuite_ia_taupunkttemperatur: AggregationTypes.AVERAGE,
    heizungssuite_ia_volumenstrom: AggregationTypes.AVERAGE,
    heizungssuite_ia_vorlaufisttemperatur_nhz: AggregationTypes.AVERAGE,
    heizungssuite_ia_vorlaufisttemperatur_wp: AggregationTypes.AVERAGE,

    heizungssuite_iw_leistungsaufnahme_vd_heizen_summe: AggregationTypes.DIV_VORTAG,
    heizungssuite_iw_leistungsaufnahme_vd_heizen_tag: AggregationTypes.MAX_BEFOR_MINOR,
    heizungssuite_iw_nhz_1: AggregationTypes.MAX,
    heizungssuite_iw_nhz_1_durch_2: AggregationTypes.MAX,
    heizungssuite_iw_nhz_2: AggregationTypes.MAX,
    heizungssuite_iw_vd_heizen: AggregationTypes.MAX,
    heizungssuite_iw_vd_kühlen: AggregationTypes.MAX,
    heizungssuite_iw_verdichter: AggregationTypes.MAX,
    heizungssuite_iw_waermemenge_nhz_heizen_summe: AggregationTypes.DIV_VORTAG,
    heizungssuite_iw_waermemenge_vd_heizen_summe: AggregationTypes.DIV_VORTAG,
    heizungssuite_iw_waermemenge_vd_heizen_tag: AggregationTypes.MAX_BEFOR_MINOR,

    heizungssuite_ds_hauptversionsnummer: AggregationTypes.MAX,
    heizungssuite_ds_nebenversionsnummer: AggregationTypes.MAX,
    heizungssuite_ds_ok: AggregationTypes.MAX,
    heizungssuite_ds_revisionsnummer: AggregationTypes.MAX,
    heizungssuite_ds_sg_ready: AggregationTypes.MAX,
    heizungssuite_ds_software: AggregationTypes.MAX,
    heizungssuite_ds_wpm_3i: AggregationTypes.MAX,
};
